name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: compiler
    steps:
      - name: Checkout compiler
        uses: actions/checkout@v4
        with:
          path: compiler
      - name: Checkout tests
        uses: actions/checkout@v4
        with:
          repository: kaitai-io/kaitai_struct_tests
          path: tests
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - uses: sbt/setup-sbt@v1
      - name: Run tests
        run: sbt test
